# Generated by Django 3.0.7 on 2020-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=10),
        ),
    ]
