# Generated by Django 3.0.7 on 2020-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200624_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_order',
            name='Price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subs_order',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
