# Generated by Django 3.0.7 on 2020-06-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200624_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='extra_cheese',
        ),
        migrations.AddField(
            model_name='subs_order',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
    ]
