# Generated by Django 3.0.7 on 2020-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_subs_no_of_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
