# Generated by Django 3.0.7 on 2020-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_order',
            name='ordered',
            field=models.BooleanField(default=0),
        ),
    ]
