# Generated by Django 3.0.7 on 2020-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pizza_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta_order',
            name='ordered',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='platter_order',
            name='ordered',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='salad_order',
            name='ordered',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='subs_order',
            name='ordered',
            field=models.BooleanField(default=0),
        ),
    ]
