# Generated by Django 3.0.8 on 2020-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubedl', '0003_category_playlist_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
