# Generated by Django 3.0.8 on 2020-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubedl', '0004_auto_20200728_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
